set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[2 q'
set -sg escape-time 0
set -g xterm-keys on
set -g status-right " %I:%M %p [#(whoami)]"
set -g default-command "${SHELL}"

set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'


unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind-key -r ^ last-window
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/workspace/dev/todo.md"

# forget the find window.  That is for chumps
bind-key -r f neww /home/jjoyner/dev-env/.local/scripts/tmux-sessionizer
bind -r r source-file $HOME/.tmux.conf \; display-message "tmux.conf reloaded"
