shell /bin/zsh

allow_remote_control yes
listen_on unix:/tmp/mykitty

shell_integration no-title

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
background #000000
# END_KITTY_THEME
cursor_blink_interval 0

term xterm-256color

cursor_shape beam

# Increase line height by 2 pixels (you can also use percentages like 110%)
# modify_font cell_height 2px
